### ISSUE TITLE
potential lookahead bias

### ISSUE THREAD

**Issue by mg64ve** [localhorst87/trading_rl#1]
Nice code, thanks for sharing.
I have a doubt on the following:

```
tradingState = self.actionSpace.do(action)
reward = self.rewarder.getReward(self.dataset, action)
observation = self.dataset.__next__()
```

I guess you are basically calculating reward before moving ahead the timestep.
What do you think?

**Comment by localhorst87** [comment]
Hi mg64ve,
thanks for your feedback! 

Actually the error is the naming :) it must be "nextObservation" instead of "observation".
The action and the reward is calculated with the information of the previous observation.
I'm going to push the latest commit where the environment is implemented in the agent and then it becomes obvious within the implementation.

**Comment by mg64ve** [comment]
Hi,

I totally disagree with your opinion.
Your are right when you say self.dataset.\_\_next\_\_() returns the next observation.
Before doing that it increments the counter.
But when you start from an observation and you take an action on that observation,
before calculating the reward, you should increment the counter.
Otherwise your reward would be calculated on the current observation that you already have.
So the actions you should take are:

- from current observation predict an action. This action would have effect on future data not on current data
- increment the counter in the way you move ahead one step
- calculate the reward
- get next observation without incrementing the counter (it is already incremented)

I am pretty sure it is not only the name but the logic which is wrong.
I hope this helps

**Comment by localhorst87** [comment]
Hi, 

ok I got what you mean... Considering the system from a general perspective you are right. I built up my implementation for the opening agent around the fashion I'm following in the step method. So what I'm actually doing to train the agent to open a position:
- saving the sample on when the position was opened
- considering all following samples (not only those of the current observation!) of the dataset to calculate the reward 
- close the episode (so no further action is possible when I train to open a position)

This is because for opening a position I want to have values returned, so in the end the user can control the opening of a position in adjusting risk factors. Otherwise the agent had to learn a new policy.
For general implementations it's right to first increment the counter and calculating the reward afterwards. But I don't see a look ahead bias as the agent is not working with data it wouldn't be able to acquire in online mode to decide on actions. Or where do you potentially see it? 
And: The rewarder calculates rewards with the information about the action and on which sample the action was performed. So there's no need to separate incrementation from returning the current observation. Note: The rewarder does not only gets the current observation passed, but the complete dataset, for being able to implement reward calculations according to different strategies.
So the rewarder does know all the future data and that is okay as the reward is only used for training, not for deciding on an action.

**Comment by mg64ve** [comment]
Hi,

I see now you have kind of complex Rewarder class, but do you have any evidence this bias is not relevant?
I haven't executed your code in my machine yet, so I don't know what sort of results you are getting.
Do you have any plan to put some result an graph in your notebook?

**Comment by localhorst87** [comment]
Hi,

the logic contains the evidence: 
What is happening inside an episode?
- decide which action to perform, based on the last observation
- calculate the reward
- get the next observation
- ...

The reward function considers an amount of the next samples to calculate the quality of the action. It does not only take into account the one and only next sample, so even with the error you mentioned above (thanks for that :-) ) there isn't a classical look ahead bias present. 

Of course I will add a graph. Got some time the next days!

**Comment by localhorst87** [comment]
@mg64ve 
notebook with results is online:

https://github.com/localhorst87/trading_rl/blob/master/training_example.ipynb
